# Project-wide Gradle settings

# JVM arguments used for the Gradle Daemon
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# AndroidX libraries mapping
android.useAndroidX=true
android.enableJetifier=true

# Version of flipper SDK to use with React Native
FLIPPER_VERSION=0.201.0

# Use architectural options
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Enable/disable features
hermesEnabled=true
newArchEnabled=false
